ignore = [
    "mystiko_crypto/tests/shamir_tests.rs",
    "mystiko_protocol/tests/types_tests.rs",
]

reorder_imports = true

# Sets the maximum width of a single line of code.
# Defaults 100.
max_width = 120
