[workspace]
members = [
    "mystiko_abi",
    "mystiko_abi_generate",
    "mystiko_crypto",
    "mystiko_protocol",
    "mystiko_database",
    "mystiko_downloader",
    "mystiko_fs",
    "mystiko_indexer_client",
    "mystiko_storage",
    "mystiko_storage_sqlite",
    "mystiko_utils",
    "mystiko_config"
]

exclude = []