[workspace]
members = [
    "mystiko_abi",
    "mystiko_abi_generate",
    "mystiko_crypto",
    "mystiko_database",
    "mystiko_downloader",
    "mystiko_storage",
    "mystiko_storage_sqlite",
    "mystiko_utils",
]

exclude = []