[package]
name = "mystiko_abi_generate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers-contract-abigen = { version = "2.0.0" }
regex = { version = "1.7.1" }
serde = { version = "1.0.152" }
