[package]
name = "mystiko_storage_sqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.69" }
async-trait = { version = "0.1.64" }
mystiko_storage = { version = "0.1.0", path = "../mystiko_storage" }
num-traits = { version = "0.2.15" }
serde_json = { version = "1.0.91" }
sqlx = { version = "0.6.2", features = [ "runtime-tokio-native-tls", "sqlite" ] }
tokio = { version = "1.26.0", features = ["sync"] }

[dev-dependencies]
tempfile = { version = "3.4.0" }
tokio = { version = "1.26.0", features = ["macros", "rt", "test-util"] }
mystiko_storage_macros = { version = "0.1.0", path = "../mystiko_storage_macros" }
