[package]
name = "mystiko_storage_macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
heck = { version = "0.4.1" }
Inflector = { version = "0.11.4" }
proc-macro2 = { version = "1.0.56" }
quote = { version = "1.0.27" }
syn = { version = "2.0.15" }

[dev-dependencies]
anyhow = { version = "1.0.69" }
lazy_static = { version = "1.4.0" }
mystiko_storage2 = { version = "0.1.0", path = "../mystiko_storage2" }
num-bigint = { version = "0.4", features = ["serde"] }
serde = { version = "1.0.152", features = ["derive", "rc"] }
serde_json = { version = "1.0.91" }
