[package]
name = "mystiko_utils"
version = "0.1.0"
edition = "2021"

[features]
config = ["dep:config", "dep:serde_json", "dep:serde", "dep:typed-builder"]

[dependencies]
anyhow = { version = "1.0" }
config = { version = "0.13.3" ,optional = true }
ethers-core  = { version = "2.0.4" }
hex = { version = "0.4.3" }
num-bigint = { version = "0.4.3" }
num-traits = { version = "0.2.15" }
rust_decimal = { version = "1.29.0" }
serde = { version = "1.0.152",optional = true }
serde_json = { version = "1.0.91" ,optional = true}
typed-builder = { version = "0.15.2",optional = true}


