[package]
name = "mystiko_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0" }
hex = { version = "0.4.3" }
num-bigint = { version = "0.4.3" }
num-traits = { version = "0.2.15" }
rust_decimal = { version = "1.29.0" }
ethers-core  = { version = "2.0.4" }
