[package]
name = "mystiko_types"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
napi = { version = "2.13.2", default-features = false, features = ["napi8", "serde-json"] }
napi-derive = { version = "2.13.0" }
serde = { version = "1.0.152", features = ["derive", "rc"] }