[package]
name = "mystiko_dataloader"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.69" }
mystiko_protos = { version = "0.1.0", path = "../mystiko_protos" }
serde = { version = "1.0.152", features = ["derive", "rc"] }
typed-builder = { version = "0.14.0" }