[package]
name = "mystiko_dataloader"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.69" }
async-trait = { version = "0.1.64" }
chrono = { version = "0.4.26" }
log = { version = "0.4.17" }
serde = { version = "1.0.152", features = ["derive", "rc"] }
tokio = { version = "1.26.0", features = ["sync"] }
typed-builder = { version = "0.14.0" }
thiserror = { version = "1.0", default-features = false }

mystiko_config = { version = "0.1.0", path = "../mystiko_config" }
mystiko_protos = { version = "0.1.0", path = "../mystiko_protos" }

[dev-dependencies]
futures = { version = "0.3.28" }