[package]
name = "mystiko_storage"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.69" }
async-trait = { version = "0.1.64" }
num-bigint = { version = "0.4" }
num-traits = { version = "0.2.15" }
serde_json = { version = "1.0.91" }
thiserror = { version = "1.0", default-features = false }
ulid = { version = "1.0.0" }

[dev-dependencies]
tokio = { version = "1.26.0", features = ["macros", "rt", "test-util"] }
typed-builder = { version = "0.14.0" }