[package]
name = "mystiko_storage"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = { version = "0.1.64" }
num-traits = { version = "0.2.15" }
ulid = { version = "1.0.0" }

[dev-dependencies]
tokio-test = { version = "0.4.2" }