name: build and test

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Add rust component
        run: |
          rustc --version; cargo --version; rustup --version
          rustup component add rustfmt
          rustup component add clippy
#      - name: Install
#        run: |
#          sudo apt-get install -y pkg-config libssl-dev
#          sudo apt-get install libboost-all-dev
      - name: Build
        run: RUSTFLAGS="-D warnings" ./scripts/build.sh
      - name: Check format
        run: cargo fmt --all -- --check
      - name: Run clippy
        timeout-minutes: 60
        run: cargo clippy -j 4 -- -D warnings
