name: Coverage

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - 'codecov.yml'
      - '.github/workflows/coverage.yml'
  pull_request:
    paths:
      - '**/*.rs'
      - '**/Cargo.toml'
      - '**/Cargo.lock'
      - 'codecov.yml'
      - '.github/workflows/coverage.yml'

jobs:
  coverage:
    name: Coverage on stable
    timeout-minutes: 140
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.3.0
        with:
          token: ${{ secrets.PACKAGES_TOKEN }}
          lfs: true
          submodules: recursive
          persist-credentials: false

      - name: Unzip circuits
        run: |
          ./scripts/unzip_circuits.sh

      - uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: nightly
          override: true
          profile: minimal
          components: llvm-tools-preview

      - name: Install cargo-llvm-cov cargo command
        run: cargo install cargo-llvm-cov

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Run tests
        run: cargo llvm-cov --ignore-filename-regex=mystiko_abi --lcov --no-report

      - name: Generate coverage report
        run: cargo llvm-cov --ignore-filename-regex=mystiko_abi --lcov --no-run --output-path lcov.info

      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true

      - name: Telegram Failure Notification
        uses: appleboy/telegram-action@master
        if: failure()
        with:
          message: ❗ Run coverage failed for [${{ github.repository }}](https://github.com/${{ github.repository }}/actions) because of ${{ github.actor }}
          format: markdown
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
