[package]
name = "mystiko_config"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mystiko_utils = { version = "0.1.0", path = "../mystiko_utils" }
num-bigint = { version = "0.4.3" }
regex = { version = "1.7.1" }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = { version = "1.0.91" }
strum = { version = "0.24.1", features = ["derive"] }
validator = { version = "0.15", features = ["derive"] }
flame = { version = "0.2.2" }
flamer = { version = "0.4.0" }

[dev-dependencies]
tokio = { version = "1.26.0", features = ["macros", "rt", "test-util"] }
lazy_static = { version = "1.4.0" }
async_once = { version = "0.2.6" }

[profile.bench]
debug = true
